name: laravel-deployment
on:

  push:

    branches: [ main]

jobs:

 deploy:

   runs-on: ubuntu-latest

   steps:

    - uses: actions/checkout@v2

    - name: Create ZIP deployment package

      run: zip -r deploy.zip ./

    - name: Deploy to Elastic Beanstalk

      uses: einaregilsson/beanstalk-deploy@v18

      with:

        aws_access_key: ${{ secrets.LARAVEL_ACCESS_KEY }}

        aws_secret_key: ${{ secrets.LARAVEL_SECRET_KEY }}

        application_name: laravelapp

        environment_name: Laravelapp-env

        existing bucket_name: ${{ secrets.LARAVEL_BUCKET }}

        region: us-east-1

        version label: ${{ github.sha}}

        deployment package: deploy.zip